config/routes.rb
Rails.application.routes.draw do

  get 'votes/new'
  get 'votes/create'
  get 'votes/destroy'
  get 'articles/index'
  get 'articles/new'
  get 'articles/create'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :users, only: [:new, :destroy, :create, :show]
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end
  resources :categories, only: [:index, :new, :new, :create, :update, :show]

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :avatar, attached: true
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :text, presence: true, length: { minimum: 10, maximum: 225 }
  validates :user_id, presence: true
  validates :category_id, presence: true

  belongs_to :user
  has_many :categories
  acts_as_votable
  has_one_attached :avatar

  def score
    votes.count
  end

  def self.highest_voted
    self.order('cached_votes_up DESC')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 40 }
  validates :priority, presence: true, inclusion: 1..5

  has_many :articles, dependent: :destroy

  scope :for_navbar, -> { limit(5) }

  def first_article
    articles.includes(:avatar_attachment).order(created_at: :desc).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true, length: { minimum: 3, maximum: 30 }

  has_many :articles
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :article, uniqueness: { scope: :user }
  validates :user, uniqueness: { scope: :article }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      @current_user
    else
      false
    end
  end

  helper_method :current_user

  def require_user
    unless current_user
      flash[:notice] = 'You must be logged in to access this page'
      redirect_to new_user_path
      false
    end
  end

  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :current_user
  before_action :require_user
  before_action :find_article, only: %i[show update destroy]

  def index
    @articles = Article.all.order(cached_votes_score: :desc)
    @categories = Category.all.includes(:articles).order(priority: :desc)
  end

  def new
    @article = Article.new
    @category = Category.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @article = @current_user.articles.new(article_params)
    @article.category_id = params[:category_id]
    if @article.save
      flash[:success] = 'New article created!'
      redirect_to categories_path
    else
      unless @article.avatar.attached?
        flash[:error] = 'No image attached, please add an image'
      end
      if @article.title.length < 3
        flash[:error] = 'Your title must have at least 3 characters'
      end
      if @article.text.length > 225
        flash[:error] = 'Your text is too long! Make it maximum 225 characters'
      end
      redirect_to root_path, notice: message
    end
  end

  def show
    @article = Article.find(params[:id])
    @articles = Article.all.order(cached_votes_up: :desc)
    @categories = Category.all.includes(:articles).order(cached_votes_up: :desc)
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @article = Article.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
    @article.category_id = params[:category_id]
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = 'Article was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end

  def upvote
    @article = Article.find(params[:id])
    @article.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @article = Article.find(params[:id])
    @article.downvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category_id, :avatar)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: %i[create new]
  def index
    @categories = Category.all.includes(:articles).order(priority: :desc)
    @voted_article = Article.highest_voted.includes(:avatar_attachment)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save!
    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @category = Category.includes(:articles).find(params[:id])
  end

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Category was successfully updated'
      redirect_to @category
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(name: params[:name])

    if @user
      session[:user_id] = @user.id
    else
      flash[:error] = 'Something went wrong, make sure your username is correct'
    end
    redirect_to root_path
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    @vote = current_user.votes.new(article_id: params[:article_id])

    if @vote.save
      flash[:success] = 'Vote successfully created'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end

  def destroy
    @vote = Vote.find_by(article_id: params[:article_id], user_id: current_user.id)
    if @vote.delete
      flash[:success] = 'Vote was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end
end

app/helpers/artcatego_helper.rb
module ArtcategoHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_newarticle.html.erb
<div class="container-fluid ps-md-0">
<div class="row g-0">
  <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
  <div class="col-md-8 col-lg-6 bg-white">
    <div class="login d-flex align-items-center py-5">
      <div class="container">

          <div class="row">
          <div class="col-md-9 col-lg-8 mx-auto">                            
          <% if flash[:error] %>
            <div class="alert alert-info"><%= flash[:error] %></div>
          <% end %>
            <h3 class="login-heading mb-4">Create your articles</h3>


                <div class="section">
                    <div class="container">
                        <div class="columns is-centered">
                            <div class="column is-4">
                            <%= form_with model: @article do |form| %>
                              <%= form.label :title, "Article Title" %>
                              <%= form.text_field :title %></br>
                              <%= form.label :text, "Add your text here" %>
                              <%= form.text_field :text, class: 'label' %></br>
                              <%= form.label "Image" %>
                              <%= form.file_field :avatar %></br>
                              <div class="control">
                              <%= form.label :category %>
                              <%= select_tag :category_id, options_for_select(@categories), class: 'input' %>
                            </div>
                              <%= form.submit%>
                             <% end %>

                            </div>
                        </div>
                    </div>
                </div>







          </div>
        </div>




      </div>
    </div>
  </div>
</div>
</div>

app/views/articles/_vote.html.erb
<% @articles.each do |article| %>
    <h4><%= link_to article.title, article %><br>
      Submitted <%= time_ago_in_words(article.created_at) %> 
    </h4>
<% end %>

app/views/articles/edit.html.erb
<main>
  <%= render 'newarticle' %>
</main>

app/views/articles/new.html.erb
<main>
  <%= render 'newarticle' %>
</main>

app/views/articles/show.html.erb
<div class="mt-2 pt-2 mb-2 pb-2">

    <div class="mt-5 pt-5 mb-5">
    <main class="blog-post">
    <div class="container">      

        <h2 class="edica-page-title pb-1 shadowy"><%= @article.title %></h2>
          <p class="edica-blog-post-meta">
            <% if @article.user_id == current_user.id %>
              <%= link_to 'Edit', edit_article_path(@article.id), class: 'art-card__button-link btn-warning' %>
              <%= link_to 'Delete', article_path(@article.id), method: :delete, class: 'art-card__button-link btn-danger' %>
            <% end %>
            <%= @article.get_upvotes.size %> Votes • 
            <%= link_to like_article_path(@article.id), method: :put do %>
              Vote! • 
            <% end %>          
            <%= link_to dislike_article_path(@article.id), method: :put do %>
              Downvote
            <% end %> 
          </p>
          <section class="blog-post-featured-img d-flex justify-content-center">
            <% if @article.avatar.attached? %>
              <image src="<%=(url_for(@article.avatar)) %>">
            <% end %>
          </section>
          <section class="post-content">
              <div class="row">
                <div class="col-lg-9 mx-auto" >

                </div>
              </div>            
          </div>

              
    </div>
    <div class="pt-5 pb-5 container d-flex justify-content-center">
    <%= link_to 'Back', :back, class: 'btn btn-light' %>
  </div>
    </main>
  </div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/categories/_categories.html.erb
<div class="container">
  <div class="row" >  
    <% @categories.each do |cat| %>                
          <% cat.articles.highest_voted.take(1).each do |c| %> 
            <div class="col-4 justify-content-evenly text-center p-2"> 
              <div class="col p-2 cat-grid-cont">  
                <h3><%= link_to "#{cat.name}", category_path(cat.id), class: 'text-dark' %></h3></br>
                <h4><%= c.title %></h4></br>
                <div class="thumbnail m-auto">
                  <%= image_tag(c.avatar, class: 'thumbnail-img') if c.avatar.attached? %></br>
                </div>
                <span></span></br>
              </div>
            </div>
          <% end %>                         
    <% end %>
  </div>
</div>

app/views/categories/_newcategory.html.erb
<div class="container-fluid ps-md-0">
<div class="row g-0">
  <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
  <div class="col-md-8 col-lg-6 bg-white">
    <div class="login d-flex align-items-center py-5">
      <div class="container">

          <div class="row">
          <div class="col-md-9 col-lg-8 mx-auto">
            <h3 class="login-heading mb-4">Add a new category</h3>


                <div class="section">
                    <div class="container">
                        <div class="columns is-centered">
                            <div class="column is-4">
                
                              <div class="form-container">
                                <%= form_with model: @category, class: 'form' do |f| %>
                                  <div class="control">
                                    <%= f.label :name %>
                                    <%= f.text_field :name, class: 'input' %>
                                  </div>
                                  <div class="control">
                                    <%= f.label :priority %>
                                    <%= f.select :priority, [1, 2, 3, 4, 5], class: 'input' %>
                                  </div>
                                  <%= f.submit class: 'form__button | text-is-white' %>
                                <% end %>
                              </div>

                            </div>
                        </div>
                    </div>
                </div>




              <div class="form-check mb-3">

              </div>


          </div>
        </div>




      </div>
    </div>
  </div>
</div>
</div>

app/views/categories/_vote.html.erb
<%= form_for @articles.votes.build do |f| %>
    <%= f.hidden_field :user, value: current_user %>
    <%= f.submit 'Vote', class: 'vote-submit' %>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<main class="p-5">
</main>
<main class="container">

<div class="container p-1 main-article col-lg text-center cat-grid-cont mt-5 mb-5">

<% @voted_article.take(1).each do |vot| %>       
    <h3><%= vot.title %></h3></br>
    <% if flash[:error] %>
    <div class="alert alert-info"><%= flash[:error] %></div>
    <% end %> 
    <p class="edica-blog-post-meta">
    • <%= vot.get_upvotes.size %> Votes • 
    </p>
    <%= image_tag(vot.avatar,class: 'head-img') %></br>
    <div class="m-3"></div>
    <h5 class="text-justify"><%= vot.text %></h5></br>
    <%= link_to "See more", article_path(vot) %>
  </div>
<% end %>
</div>

    <div class="container p-1">
      <%= render 'categories' %>
    </div>
  </div>
</main>


<main class="p-1">
  <div class="">
  </div>
</main>

app/views/categories/new.html.erb
<main>
  <%= render 'newcategory' %>
</main>

app/views/categories/show.html.erb
<div class="mt-2 pt-2">

  <div class="mt-5 pt-5 mb-5">

    <main class="blog-post">

      <div class="container">
      
        <h1 class="edica-page-title pb-1"><%= @category.name %></h1>        
        <% @category.articles.each do |art| %>
          <div class="pt-5 pb-5">
            <h2 class="edica-page-title pb-1"><%= art.title %></h2>
            <h5 class="edica-page-title pb-1">By: <%= art.user.name %></h5>
              <p class="edica-blog-post-meta">
              <% if logged_in? %>
                <% if art.user_id == current_user.id %>
                  <%= link_to 'Edit', edit_article_path(art.id), class: 'art-card__button-link badge badge-info' %> • 
                  <%= link_to 'Delete', article_path(art.id), method: :delete, class: 'art-card__button-link badge badge-danger' %> • 
                <% end %>
              <% end %>
                <%= art.get_upvotes.size %> Votes • 
                <%= link_to like_article_path(art.id), method: :put do %>
                  Vote!
                <% end %> • 
                <%= link_to dislike_article_path(art.id), method: :put do %>
                  Downvote
                <% end %> 
              </p>
              
              <section class="blog-post-featured-img d-flex justify-content-center">
                <% if art.avatar.attached? %>
                  <image src="<%=(url_for(art.avatar)) %>">
                <% end %>
              </section>

              <section class="post-content">
                  <div class="row">
                      <div class="col-lg-9 mx-auto text-center" data-aos="fade-up">
                      <%= art.text %>
                      </div>
                  </div>            
              </section>
          </div>
        <% end %>



      </div>

    </main>

  </div>

</div>

  <div class="pt-5 pb-5 container d-flex justify-content-center">
    <%= link_to 'Back', :back, class: 'btn btn-light' %>
  </div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="text-center text-lg-start bg-light text-muted">

  <section
    class="row p-4 border-bottom justify-content-between"
  >

    <div class="text-center col p-4">
    © 2021 Sunny Díaz
    </div>

    <div class="col text-center p-4">
      <span>Get in touch on social media:</span>
    </div>

    <div class="col row pt-4 pb-4">         
            <a href="https://twitter.com/josfrant6" class="col-3 text-muted">
                <i class="fab fa-twitter fa-2x"></i>
            </a>
            <a href="https://www.instagram.com/webdev.sunnydiaz/" class="col-3 text-muted">
                <i class="fab fa-instagram fa-2x"></i>
            </a>
            <a href="https://www.linkedin.com/in/jose-f-silva" class="col-3 text-muted">
                <i class="fab fa-linkedin fa-2x"></i>
            </a>
            <a href="https://github.com/sunnySparks" class="col-3 text-muted">
                <i class="fab fa-github fa-2x"></i>
            </a>
    </div>

  </section>

</footer>

app/views/layouts/_header.html.erb
<header>
    <div class='container'>
        <%= image_tag '', class: 'page_logo'%>

        <nav>
            <ul>
                <li></li>
            </ul>
        </nav>
    </div>
</header>

<div class="banner">
  <%= link_to article_path(@voted_article) do %>
  <%= image_tag(url_for(display_image(@voted_article)), class: 'banner__img') %>
  <div class="banner__content">
    <h1 class="banner__content-title">
      <%= @voted_article.title %>
    </h1>
    <p class="banner__content-description">
      <%= truncated_card_content(@voted_article.content) %>
    </p>
  </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-expand-md navbar-dark fixed-top text-dark'>
<li class="nav-item">
      <%= link_to image_tag("logo.png", size: "100x75", :alt => "logo"), categories_url %>
</li>
<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarsExampleDefault' aria-controls='navbarsExampleDefault' aria-expanded='false' aria-label='Toggle navigation'>
  <span class='navbar-toggler-icon'></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav m-auto pb-3">
    <li class="nav-item active">
      <%= link_to 'New Article', new_article_url, class: 'text-white' %>
    </li>
    <li class="nav-item">
      <%= link_to 'New Category', new_category_url, class: 'text-white' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Categories', categories_url, class: 'text-white' %>
    </li>
     
      <% if logged_in? %>
        <li>  
          <%= link_to "Log out", logout_path, class: 'text-white' %>
        </li>
        <li>  
          <span class="text-white">Welcome, <%= current_user.name %>!</span>
        </li>
      <% else %>
        <li>  
          <%= link_to "Log In", login_url, class: 'text-white' %>
        </li>
        <li>  
          <p class='text-white'>|</p>
        </li>
        <li>  
          <%= link_to "Sign up", new_user_path, class: 'text-white' %>
        </li>
      <% end %>
    </li>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="es">
  <head>
    <title>LifestyleArticles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://blog.nubecolectiva.com/wp-content/uploads/2018/08/faviconcc.png">
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    
  </head>
 
  <body>
    <header class='mt-0 pt-0'>
      <%= render 'layouts/navbar' %>
    </header>
    <%= yield %>
    
    <footer class='mt-0 pt-0'>
    <%= render 'layouts/footer' %>
  </footer>
  </body>
</html>

app/views/users/_header.html.erb
<%= render 'common/flash' %>
<div class="banner">
  <%= link_to article_path(@voted_article) do %>
  <%= image_tag(url_for(display_image(@voted_article)), class: 'banner__img') %>
  <div class="banner__content">
    <h1 class="banner__content-title">
      <%= @voted_article.title %>
    </h1>
    <p class="banner__content-description">
      <%= truncated_card_content(@voted_article.content) %>
    </p>
  </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
  <div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6 bg-white">
      <div class="login d-flex align-items-center py-5">
        <div class="container">

          

          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Create your account here</h3>




              <div class="section">
              <div class="container">
                <div class="columns is-centered">
                  <div class="column is-4">
                  <% if flash[:error] %>
                    <div class="alert alert-info"><%= flash[:error] %></div>
                  <% end %>
                      <%= form_for User.new do |f| %>
                          <%= f.text_field :name %><br>
                          <%= f.label :name %><br>
                          <%= f.submit "Create Account", class: "btn btn-large btn-primary" %>
                      <% end %>
          
                  </div>
                </div>
              </div>
            </div>
          



                <div class="form-check mb-3">

                </div>

                <div class="form-check mb-3">
                <p>Do you have an account?</p>
                  <%= link_to "Log In", login_url %>
                </div>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<div class="section">
<div class="container">
  <div class="columns is-centered">
    <div class="column is-4">
    <h2 class="title is-2 is-spaced has-text-centered">Have an account? Log In</h2>

    <%= form_for(:session, url: login_path) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "input", required: true %>
        <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
      <% end %>

    </div>
  </div>
</div>
</div>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>